[2025-10-17T18:30:01.218+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: databricks_dag.run_now scheduled__2025-10-15T00:00:00+00:00 [queued]>
[2025-10-17T18:30:01.240+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: databricks_dag.run_now scheduled__2025-10-15T00:00:00+00:00 [queued]>
[2025-10-17T18:30:01.241+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-10-17T18:30:01.276+0000] {taskinstance.py:1327} INFO - Executing <Task(DatabricksRunNowOperator): run_now> on 2025-10-15 00:00:00+00:00
[2025-10-17T18:30:01.290+0000] {standard_task_runner.py:57} INFO - Started process 573 to run task
[2025-10-17T18:30:01.300+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'databricks_dag', 'run_now', 'scheduled__2025-10-15T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/databricks_dag.py', '--cfg-path', '/tmp/tmp5dpaydj_']
[2025-10-17T18:30:01.307+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask run_now
[2025-10-17T18:30:01.452+0000] {task_command.py:410} INFO - Running <TaskInstance: databricks_dag.run_now scheduled__2025-10-15T00:00:00+00:00 [running]> on host 444659dc247e
[2025-10-17T18:30:01.642+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrei' AIRFLOW_CTX_DAG_ID='databricks_dag' AIRFLOW_CTX_TASK_ID='run_now' AIRFLOW_CTX_EXECUTION_DATE='2025-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-15T00:00:00+00:00'
[2025-10-17T18:30:01.662+0000] {base.py:73} INFO - Using connection ID 'databricks_conn' for task execution.
[2025-10-17T18:30:01.797+0000] {databricks_base.py:429} INFO - Using token auth.
[2025-10-17T18:30:02.935+0000] {databricks.py:52} INFO - Run submitted with run_id: 57136749155090
[2025-10-17T18:30:02.936+0000] {databricks_base.py:429} INFO - Using token auth.
[2025-10-17T18:30:03.355+0000] {databricks_base.py:429} INFO - Using token auth.
[2025-10-17T18:30:03.793+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/databricks/operators/databricks.py", line 673, in execute
    _handle_databricks_operator_execution(self, hook, self.log, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/databricks/operators/databricks.py", line 61, in _handle_databricks_operator_execution
    if run_state.is_terminal:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/databricks/hooks/databricks.py", line 82, in is_terminal
    ).format(self.life_cycle_state)
airflow.exceptions.AirflowException: Unexpected life cycle state: QUEUED: If the state has been introduced recently, please check the Databricks user guide for troubleshooting information
[2025-10-17T18:30:03.801+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=databricks_dag, task_id=run_now, execution_date=20251015T000000, start_date=20251017T183001, end_date=20251017T183003
[2025-10-17T18:30:03.830+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 4 for task run_now (Unexpected life cycle state: QUEUED: If the state has been introduced recently, please check the Databricks user guide for troubleshooting information; 573)
[2025-10-17T18:30:03.885+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-10-17T18:30:03.921+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
